# Generated by Django 5.2 on 2025-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_application_applied_at_application_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
